"""
html_report.py

Generates an HTML report for ReconX.
"""

import os
from datetime import datetime


class HTMLExporter:

    @staticmethod
    def export(results, target, elapsed):

        os.makedirs("exports", exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        filename = f"exports/{target.replace('.', '_')}_{timestamp}.html"

        rows = ""

        for item in results:

            banner = item["banner"].replace("<", "&lt;").replace(">", "&gt;")

            rows += f"""
            <tr>
                <td>{item['port']}</td>
                <td>{item['service']}</td>
                <td>{banner}</td>
            </tr>
            """

        html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>PortScanner-Pro Scan Report</title>

<style>

body{{
font-family:Arial;
background:#f4f6f8;
padding:40px;
}}

.container{{
background:white;
padding:30px;
border-radius:10px;
box-shadow:0 0 15px rgba(0,0,0,.15);
}}

h1{{
color:#1565c0;
}}

table{{
width:100%;
border-collapse:collapse;
margin-top:20px;
}}

th{{
background:#1565c0;
color:white;
padding:12px;
}}

td{{
padding:10px;
border-bottom:1px solid #ddd;
}}

.info{{
margin-top:15px;
font-size:17px;
}}

.footer{{
margin-top:30px;
color:gray;
}}

</style>

</head>

<body>

<div class="container">

<h1>PortScanner-Pro Network Scan Report</h1>

<div class="info">

<b>Target :</b> {target}<br>
<b>Scan Time :</b> {elapsed:.2f} Seconds<br>
<b>Total Open Ports :</b> {len(results)}

</div>

<table>

<tr>

<th>Port</th>
<th>Service</th>
<th>Banner</th>

</tr>

{rows}

</table>

<div class="footer">

Generated by PortScanner-Pro v1.0

</div>

</div>

</body>

</html>
"""

        with open(filename, "w", encoding="utf-8") as file:
            file.write(html)

        return filename